services:
  cgvmate-api:
    image: 'cgvmate-api:v0.5.0'
    restart: always
    container_name: cgvmate-api
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING};
      - IV=${IV}
      - KEY=${KEY}
    ports:
      - 8080:8080