// <auto-generated />
using CgvMate.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CgvMate.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240518143341_ChangeViewCountToBigInt")]
    partial class ChangeViewCountToBigInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CgvMate.Api.Views", b =>
                {
                    b.Property<long>("EventIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("EventIndex"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("EventIndex");

                    b.ToTable("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
