// <auto-generated />
using CgvMate.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CgvMate.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240618072747_Refactoring")]
    partial class Refactoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CgvMate.Data.Entities.Cgv.GiveawayEvent", b =>
                {
                    b.Property<string>("EventIndex")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DDay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("EventIndex");

                    b.ToTable("GiveawayEvents");
                });

            modelBuilder.Entity("CgvMate.Data.Entities.LotteCinema.Event", b =>
                {
                    b.Property<string>("EventID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CinemaAreaCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CinemaAreaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CinemaID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CinemaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CloseNearYN")
                        .HasColumnType("int");

                    b.Property<int>("DevTemplateYN")
                        .HasColumnType("int");

                    b.Property<string>("EventClassificationCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventCntnt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventNtc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EventSeq")
                        .HasColumnType("int");

                    b.Property<string>("EventTypeCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EventWinnerYN")
                        .HasColumnType("int");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ImageDivisionCode")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProgressEndDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProgressStartDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RemainsDayCount")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
