name: CgvMate.Api

on:
  push:
    paths:
      - 'web/CgvMate.Api/**'  # web 폴더에 푸시될 때 실행되도록 설정
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: 빌드
      run: cd web/CgvMate.Api && bash ./publish.sh
      
    - name: 환경변수 파일 생성
      run: |
        cd web
        touch .env
        echo "${{ secrets.DotEnv }}" > .env  # .env 파일 덮어쓰기
        cat .env
      
    - name: 도커 컴포즈 실행
      run: cd web && docker compose up -d 
