name: CgvMate.Api

on:
  push:
    paths:
      - 'docker-compose.yml'
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: 빌드
      run: cd CgvMate.Api && bash ./publish.sh
      
    - name: 환경변수 파일 생성
      run: |
        touch .env
        echo "${{ secrets.DotEnv }}" > .env
      
    - name: 도커 컴포즈 실행
      run: docker compose up -d 
