name: CgvMate.Client

on:
  push:
    paths:
      - 'web/CgvMate.Client/**'  # web 폴더에 푸시될 때 실행되도록 설정
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: 배포
      run: cd web/CgvMate.Client && dotnet publish --configuration Release -o /mnt/bind_mount/cgvmate.com
      
