name: CgvMate.Client

on:
  push:
    paths:
      - 'CgvMate.Client/**'
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: 배포
      run: cd CgvMate.Client && dotnet publish --configuration Release -o /mnt/bind_mount/cgvmate.com
      
