name: CgvMate.Client

on:
  push:
    paths:
      - 'cgvmate-web/**'
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: npm install
      run: cd cgvmate-web && npm install

    - name: 빌드
      run: cd cgvmate-web && npm run build

    - name: 이전 파일 삭제
      run: rm -rf /mnt/bind_mount/cgvmate.com/build

    - name: 배포
      run: mv cgvmate-web/build /mnt/bind_mount/cgvmate.com
      
